apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  outputs:
   - name: vector-to-azure-blob
     type: fluentdForward 
     url: 'tcp://vector.vector.svc.cluster.local:24224' 
  pipelines:
   - name: forward-to-fluentd-vector
     inputRefs:  
     - application
     - audit
     outputRefs:
     - vector-to-azure-blob
     parse: json 
