---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector
  labels:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/version: "0.32.1-distroless-libc"
data:
  aggregator.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      fluent:
        address: 0.0.0.0:24224
        type: fluent
    sinks:
      stdout:
        type: console
        inputs: [fluent]
        encoding:
          codec: json
      aws_s3:
        type: "aws_s3"
        inputs: [fluent]
        bucket: YOUR_BUCKET_NAME
        region: YOUR_REGION_NAME
        encoding:
          codec: json
